feat(async-sdk-cpp):  added all async features to source/rest/public
bitwyre/sdk pull request #28
Opened 2021-09-08 06:01 UTC by leannejdong

added async version of all `get()` function under `cpp/source/rest/public` and their unit tests (under `cpp/source/unittest`)

2021-09-08 11:12 UTC, sdmg15 commented
There is an empty file `MockDepth.hpp` I guess you have to remove it

2021-09-08 13:56 UTC, sdmg15 requested changes

2021-09-08 13:56 UTC, sdmg15 commented on cpp/CMakeFiles/cmake.check_cache
> +# This file is generated by cmake for dependency checking of the CMakeCache.txt file
You have to delete the folder CMakeFiles

2021-09-08 13:56 UTC, sdmg15 commented on cpp/README.md
> +
This part of explanation should not go inside this subdirectory readme. I think it will more worthful inside the main repository readme

2021-09-08 13:56 UTC, sdmg15 commented on cpp/README.md
> +make
This one is not necessary

2021-09-08 13:56 UTC, sdmg15 commented on cpp/README.md
> +The `create` command will update our local cache and we can run the examples with the updates.
The pronoun here sounds misleading. You may need to replace the `we` by `you`, `our` to `your`

2021-09-08 13:56 UTC, sdmg15 commented on cpp/source/rest/public/CryptoAsset.hpp
> +    }
Please leave space between methods implementations

2021-09-08 13:56 UTC, sdmg15 commented on cpp/source/rest/public/Time.hpp
> +      return std::async(std::launch::async, [/*this*/](){return get<Dispatcher>();});
Please remove this comment

2021-09-08 13:56 UTC, sdmg15 commented on cpp/source/unittest/publicApi.test.cpp
> +TEST_CASE("AsyncAsset Request", "[rest][public][future][asset]") {
Please replace `future` with `async`

2021-09-08 13:56 UTC, sdmg15 commented on cpp/source/unittest/publicApi.test.cpp
> +TEST_CASE("Contract AsyncRequest", "[rest][public][future][contract]") {
Same here replace `future` with `async`

2021-09-08 14:33 UTC, dendisuhubdy approved these changes

2021-09-08 15:06 UTC, leannejdong reviewed
all suggestions been adapted.

2021-09-08 15:06 UTC, leannejdong commented on cpp/CMakeFiles/cmake.check_cache
> +# This file is generated by cmake for dependency checking of the CMakeCache.txt file
Done

2021-09-08 15:06 UTC, leannejdong commented on cpp/README.md
> +
I moved the cpp specific discussion to sdk main

2021-09-08 15:06 UTC, leannejdong commented on cpp/README.md
> +The `create` command will update our local cache and we can run the examples with the updates.
pronoun fixed to `you` and `your`

2021-09-09 15:24 UTC, sdmg15 commented on README.md
> +pointing to our production cluster will be used.
These lines are a bit too much C++ SDK specific. You may need to adapt them to reflect the concept more globally. 

Those lines should instead go inside the sdk/cpp readme imho

2021-09-09 19:25 UTC, leannejdong commented on README.md
> +pointing to our production cluster will be used.
the 3 lines moved to cpp readme now.

2021-09-10 10:13 UTC, sdmg15 approved these changes

2021-09-10 10:44 UTC, dendisuhubdy approved these changes

2021-09-10 16:20 UTC, closed without merging