feat(async-sdk-cpp): added all async features to source/rest/private
bitwyre/sdk pull request #31
Opened 2021-09-13 03:07 UTC by leannejdong

Small note @sdmg15  and @dendisuhubdy:
All tests are passed (44 test cases and 121 assertions) except the float point conversion we earlier discussed.
The following issues were taken into account to pass all tests.
In `Orderinfo.hpp` , template has to be added on top in order for `getAsync` to be implemented; 
In `TransactionHistory.hpp`, the `auto static` in line15 replaced with `static auto` for consistency of the rest.
In `ClosedOrders.hpp`, line15, `static` is missing in front of `auto`. Since the `getAsync` method wraps the `get`,  the missing static will lead to the error
"`this` cannot be implicitly captured in this context " . So `static` has to be added before `auto`.

2021-09-13 03:59 UTC, dendisuhubdy approved these changes

2021-09-13 14:50 UTC, sdmg15 requested changes
I realized that you sometime don't include the header file `<future>` in some files. So please make sure you include it in all

2021-09-13 20:12 UTC, leannejdong commented
> I realized that you sometime don't include the header file `<future>` in some files. So please make sure you include it in all

#include<future> is now in `Dispatch.hpp` and a few private API include `Types.hpp` rather than `Dispatch.hpp`.

2021-09-13 20:22 UTC, leannejdong commented
The requested change has been made. Re-open in case further changes needed.

2021-09-14 07:41 UTC, sdmg15 approved these changes

2021-09-14 18:42 UTC, merged